---
booktitle: Proceedings of the Third Asian Conference on Machine Learning
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: PMLR
volume: 20
year: '2011'
start: 2011-11-14
end: 2011-11-15
published: 2011-11-17
shortname: ACML
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: HsuACML2011
month: 0
cycles: false
editor:
- given: Chun-Nan
  family: Hsu
- given: Wee Sun
  family: Lee
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Third Asian Conference on Machine Learning
    Held in South Garden Hotels and Resorts, Taoyuan, Taiwain on 14-15 November 2011

  Published as Volume 20 by the Proceedings of Machine Learning Research on 17 November 2011.

  Volume Edited by:
    Chun-Nan Hsu
    Wee Sun Lee

  Series Editors:
    Neil D. Lawrence
date_str: 14--15 Nov
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v20"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v20
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Asian Conference on Machine Learning
  url: 
  location: South Garden Hotels and Resorts, Taoyuan, Taiwain
  dates:
  - 2011-11-14
  - 2011-11-15
  number: 3
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
